env:
  - stg
  - dev
user:
  - suletta.mercury
  - miorine.rembran
  - guel.jeturk
ip_cidr:
  - 10.18X.0.0/20
  - 10.18X.16.0/20
  - 10.18X.32.0/20
identified:
  - IDENTIFIED WITH AWSAuthenticationPlugin AS 'RDS'
grant:
  - GRANT SELECT ON service_b_view.*
